### PR TITLE
Create easy shrink

### PR DESCRIPTION
**Pull request by mvleandro**
Finalizing easy-shrink api method. Please do not consider tests for Infrastructure folder at this moment.

### CODE REVIEW

**Comment by mvleandro** [comment]
@csmartins You are correct. I'll put this informations into the README file.

**Comment by mvleandro** [comment]
@csmartins Just pushed the modifications.

**Comment by csmartins** [comment]
My tests and the responses:

XPUT - http://dev-cerberus.stone.com.br:9200/test-cadu-2017.08.15

XPOST - http://localhost:5000/api/v1/easy-shrink

```
{
	"IndexName": "test-cadu-2017.08.15"
}
```
Response: 
```
{
    "body": null,
    "operation": {
        "error": {
            "className": "NullReferenceException",
            "fullClassName": "System.NullReferenceException",
            "innerError": null,
            "message": "Object reference not set to an instance of an object.",
            "source": "ElasticsearchTimeSeriesOptimizer",
            "stackTrace": "   at StoneCo.ElasticsearchTimeSeriesOptimizer.Controllers.ShrinkController.EasyShrink(ShrinkRequestBody request) in C:\\Users\\cmartins\\Source\\Repos\\semapi\\ElasticsearchTimeSeriesOptimizer\\Controllers\\ShrinkController.cs:line 83"
        },
        "failed": true
    }
}
```

**Comment by csmartins** [comment]
My tests and the responses:

XPUT - http://dev-cerberus.stone.com.br:9200/test2-cadu-2017.08.15
```
{
    "settings" : {
        "index" : {
            "number_of_shards" : 3, 
            "number_of_replicas" : 2 
        }
    }
}
```

XPOST - http://localhost:5000/api/v1/easy-shrink

```
{
	"IndexName": "test2-cadu-2017.08.15"
}
```

Response: 

```
{
    "body": {
        "response": {
            "success": true,
            "httpMethod": 2,
            "uri": "http://dev-cerberus.stone.com.br:9200/test2-cadu-2017.08.15/_shrink/test2-cadu-2017.08.15-s",
            "requestBodyInBytes": "eyAic2V0dGluZ3MiOiB7ICJpbmRleC5udW1iZXJfb2Zfc2hhcmRzIjogMSwgImluZGV4Lm51bWJlcl9vZl9yZXBsaWNhcyI6IDEsICJpbmRleC5jb2RlYyI6ICJiZXN0X2NvbXByZXNzaW9uIiB9LCAiYWxpYXNlcyI6IHsgfSB9",
            "responseBodyInBytes": null,
            "body": {},
            "httpStatusCode": 200,
            "auditTrail": [
                {
                    "event": 10,
                    "started": "2017-08-15T16:44:18.537415Z",
                    "ended": "2017-08-15T16:44:19.0125098Z",
                    "node": {
                        "uri": "http://dev-cerberus.stone.com.br:9200/",
                        "isResurrected": false,
                        "httpEnabled": true,
                        "holdsData": true,
                        "masterEligible": true,
                        "ingestEnabled": false,
                        "masterOnlyNode": false,
                        "clientNode": false,
                        "id": null,
                        "name": null,
                        "settings": {},
                        "failedAttempts": 0,
                        "deadUntil": "0001-01-01T00:00:00",
                        "isAlive": true
                    },
                    "path": "test2-cadu-2017.08.15/_shrink/test2-cadu-2017.08.15-s",
                    "exception": null
                }
            ],
            "deprecationWarnings": [],
            "successOrKnownError": true,
            "originalException": null,
            "serverError": null,
            "debugInformation": "Successful low level call on PUT: /test2-cadu-2017.08.15/_shrink/test2-cadu-2017.08.15-s\r\n# Audit trail of this API call:\r\n - [1] HealthyResponse: Node: http://dev-cerberus.stone.com.br:9200/ Took: 00:00:00.4750948\r\n# Request:\r\n{ \"settings\": { \"index.number_of_shards\": 1, \"index.number_of_replicas\": 1, \"index.codec\": \"best_compression\" }, \"aliases\": { } }\r\n# Response:\r\n<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>\r\n"
        }
    },
    "operation": {
        "error": null,
        "failed": false
    }
}
```

**Comment by csmartins** [comment]
XPUT - http://dev-cerberus.stone.com.br:9200/test3-cadu-2017.08.15
```
{
    "settings" : {
        "index" : {
            "number_of_shards" : 7, 
            "number_of_replicas" : 1 
        }
    }
}
```
XPOST - http://localhost:5000/api/v1/easy-shrink
```
{
	"IndexName": "test3-cadu-2017.08.15"
}
```
Response: 
```
{
    "body": {
        "response": {
            "success": true,
            "httpMethod": 2,
            "uri": "http://dev-cerberus.stone.com.br:9200/test3-cadu-2017.08.15/_shrink/test3-cadu-2017.08.15-s",
            "requestBodyInBytes": "eyAic2V0dGluZ3MiOiB7ICJpbmRleC5udW1iZXJfb2Zfc2hhcmRzIjogMSwgImluZGV4Lm51bWJlcl9vZl9yZXBsaWNhcyI6IDEsICJpbmRleC5jb2RlYyI6ICJiZXN0X2NvbXByZXNzaW9uIiB9LCAiYWxpYXNlcyI6IHsgfSB9",
            "responseBodyInBytes": null,
            "body": {},
            "httpStatusCode": 200,
            "auditTrail": [
                {
                    "event": 10,
                    "started": "2017-08-15T17:17:47.8357123Z",
                    "ended": "2017-08-15T17:17:48.2610136Z",
                    "node": {
                        "uri": "http://dev-cerberus.stone.com.br:9200/",
                        "isResurrected": false,
                        "httpEnabled": true,
                        "holdsData": true,
                        "masterEligible": true,
                        "ingestEnabled": false,
                        "masterOnlyNode": false,
                        "clientNode": false,
                        "id": null,
                        "name": null,
                        "settings": {},
                        "failedAttempts": 0,
                        "deadUntil": "0001-01-01T00:00:00",
                        "isAlive": true
                    },
                    "path": "test3-cadu-2017.08.15/_shrink/test3-cadu-2017.08.15-s",
                    "exception": null
                }
            ],
            "deprecationWarnings": [],
            "successOrKnownError": true,
            "originalException": null,
            "serverError": null,
            "debugInformation": "Successful low level call on PUT: /test3-cadu-2017.08.15/_shrink/test3-cadu-2017.08.15-s\r\n# Audit trail of this API call:\r\n - [1] HealthyResponse: Node: http://dev-cerberus.stone.com.br:9200/ Took: 00:00:00.4253013\r\n# Request:\r\n{ \"settings\": { \"index.number_of_shards\": 1, \"index.number_of_replicas\": 1, \"index.codec\": \"best_compression\" }, \"aliases\": { } }\r\n# Response:\r\n<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>\r\n"
        }
    },
    "operation": {
        "error": null,
        "failed": false
    }
}
```

**Comment by csmartins** [comment]
Other than my second test ("IndexName": "test2-cadu-2017.08.15") that should not work, I don't see any other problems.

**Pull request merged**
